In [ ]:
from langchain.prompts import PromptTemplate
from langchain_core.output_parsers import JsonOutputParser
import pandas as pd

In [3]:
import warnings

warnings.filterwarnings("ignore")

In [4]:
from dotenv import load_dotenv  

load_dotenv()

True

In [ ]:
from langchain_google_genai import ChatGoogleGenerativeAI
llm = ChatGoogleGenerativeAI(
    model="gemini-1.5-flash",  
    temperature=0.2,
    convert_system_message_to_human=True 
)

In [15]:
prompt_template = PromptTemplate(
    input_variables=["text", "row"],
    template_format="jinja2",
    template="""
        Examples 1:

        Subject: Create a dataset about cars
        Row: 10
        Data:
        [
        {
            "brand": "Toyota",
            "model": "Corolla",
            "year": 2022,
            "color": "Silver",
            "price": 25000,
            "fuel_type": "Hybrid"
        },
        {
            "brand": "Ford",
            "model": "Mustang",
            "year": 2021,
            "color": "Red",
            "price": 42000,
            "fuel_type": "Gasoline"
        },
        {
            "brand": "Tesla",
            "model": "Model 3",
            "year": 2023,
            "color": "White",
            "price": 45000,
            "fuel_type": "Electric"
        },
        {
            "brand": "Honda",
            "model": "Civic",
            "year": 2020,
            "color": "Blue",
            "price": 22000,
            "fuel_type": "Gasoline"
        },
        {
            "brand": "BMW",
            "model": "X5",
            "year": 2022,
            "color": "Black",
            "price": 65000,
            "fuel_type": "Diesel"
        },
        {
            "brand": "Mercedes",
            "model": "C-Class",
            "year": 2021,
            "color": "Gray",
            "price": 48000,
            "fuel_type": "Gasoline"
        },
        {
            "brand": "Audi",
            "model": "A4",
            "year": 2020,
            "color": "Green",
            "price": 38000,
            "fuel_type": "Diesel"
        },
        {
            "brand": "Volkswagen",
            "model": "Golf",
            "year": 2019,
            "color": "Yellow",
            "price": 20000,
            "fuel_type": "Gasoline"
        },
        {
            "brand": "Hyundai",
            "model": "Tucson",
            "year": 2022,
            "color": "Orange",
            "price": 28000,
            "fuel_type": "Hybrid"
        },
        {
            "brand": "Kia",
            "model": "Sportage",
            "year": 2021,
            "color": "Brown",
            "price": 26000,
            "fuel_type": "Gasoline"
        }
        ]

        Example 2:

        Subject: Generate synthetic data for worker.
        Row: 5
        Data:
        [
        {
            "name": "John Doe",
            "age": 32,
            "position": "Software Engineer",
            "salary": 75000,
            "department": "IT"
        },
        {
            "name": "Jane Smith",
            "age": 28,
            "position": "Marketing Specialist",
            "salary": 60000,
            "department": "Marketing"
        },
        {
            "name": "Michael Brown",
            "age": 45,
            "position": "Project Manager",
            "salary": 90000,
            "department": "Operations"
        },
        {
            "name": "Emily Davis",
            "age": 35,
            "position": "HR Manager",
            "salary": 65000,
            "department": "Human Resources"
        },
        {
            "name": "David Wilson",
            "age": 40,
            "position": "Sales Director",
            "salary": 85000,
            "department": "Sales"
        }
        ]

        You are a synthetic data generation tool. Generate synthetic data related to the provided 'subject'. The output must contain exactly {{row}} items. The output must be in JSON format.
        All fields in the JSON objects must be logically relevant to the given subject.
        All values must be realistic.
        Avoid duplications across rows.
        If you cannot generate the data, provide a 'Data could not be generated' message.

        Subject: {{text}}
        Row: {{row}}
        Data:
        """
    )

In [ ]:
parser = JsonOutputParser()

chain = prompt_template | llm | parser

subject = "Generate synthetic data for books in a library. columns must be atleast 9"
row_count = 3

try:
    result = chain.invoke({"text": subject, "row": row_count})
    print("Generated JSON Data:")
    print(result)

    dataset = pd.DataFrame(result)
except Exception as e:
    print(f"Error: {e}")

Generated JSON Data:
[{'title': 'The Lord of the Rings', 'author': 'J.R.R. Tolkien', 'isbn': '978-0618002255', 'genre': 'Fantasy', 'publication_year': 1954, 'publisher': 'Allen & Unwin', 'pages': 1178, 'available_copies': 5, 'language': 'English', 'average_rating': 4.5}, {'title': 'To Kill a Mockingbird', 'author': 'Harper Lee', 'isbn': '978-0061120084', 'genre': 'Historical Fiction', 'publication_year': 1960, 'publisher': 'J. B. Lippincott & Co.', 'pages': 281, 'available_copies': 3, 'language': 'English', 'average_rating': 4.2}, {'title': '1984', 'author': 'George Orwell', 'isbn': '978-0451524935', 'genre': 'Dystopian', 'publication_year': 1949, 'publisher': 'Secker & Warburg', 'pages': 328, 'available_copies': 7, 'language': 'English', 'average_rating': 4}]